title: StateSrv
email: nathan.osman@gmail.com
description: >-
  StateSrv is a cross-platform, high-performance state management application
  designed to make it easy to synchronize state between multiple clients.
